"""Generate the MSFS project and package-definition files.

`fspackagetool` is driven by two XML files: a project definition at the repo
root and a package definition per package. Both carry the package version and
title, which also live in config/package.json. Generating them from that one
file means a version bump is a one-line edit rather than three files to keep in
step and one to forget.

    python -m tools.packaging

Note on schema: the SDK has revised these formats between releases. The shapes
written here are the ones documented for the current SDK, but if
`fspackagetool` rejects them, diff against a project the SDK's own template
generator produces on your install and adjust - the version attributes are the
usual culprit. See docs/building.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

from .model import REPO_ROOT, load_json

PROJECT_NAME = "bring-the-lights-on"
PROJECT_FILENAME = f"{PROJECT_NAME}.xml"


def project_xml(package_name: str) -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>

<!--
  MSFS project definition. GENERATED - edit config/package.json and re-run
  `python -m tools.packaging`.

  Build with:  fspackagetool.exe {PROJECT_FILENAME}
-->

<ProjectDefinition Version="2" Name="{PROJECT_NAME}" OutputDir="Packages" TemporaryOutputDir="_PackageInt">
  <PackageDefinitions>
    <PackageDefinition file="PackageDefinitions\\{package_name}.xml"/>
  </PackageDefinitions>
</ProjectDefinition>
"""


def package_definition_xml(cfg: dict) -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>

<!--
  Package definition for {cfg['title']}.
  GENERATED - edit config/package.json and re-run `python -m tools.packaging`.

  The Scenery asset group compiles every .xml in PackageSources/scenery into
  BGL. Those files are themselves generated by `make build`.
-->

<AssetPackage Version="2" Name="{cfg['package_name']}">
  <ContentInfo>
    <Creator>{cfg['creator']}</Creator>
    <Title>{cfg['title']}</Title>
    <Type>{cfg['content_type']}</Type>
    <PackageVersion>{cfg['package_version']}</PackageVersion>
    <MinimumGameVersion>{cfg['minimum_game_version']}</MinimumGameVersion>
    <ReleaseNotes>
      <Neutral>
        <LastUpdate>{cfg.get('release_notes_url', '')}</LastUpdate>
      </Neutral>
    </ReleaseNotes>
  </ContentInfo>
  <AssetGroups>
    <AssetGroup Name="Scenery">
      <Type>BGL</Type>
      <AssetDir>PackageSources\\scenery</AssetDir>
      <OutputDir>scenery\\world\\scenery</OutputDir>
    </AssetGroup>
  </AssetGroups>
</AssetPackage>
"""


def write(root: Path = REPO_ROOT) -> list[Path]:
    cfg = load_json(root / "config" / "package.json")
    name = cfg["package_name"]

    project_path = root / PROJECT_FILENAME
    definition_path = root / "PackageDefinitions" / f"{name}.xml"
    definition_path.parent.mkdir(parents=True, exist_ok=True)

    project_path.write_text(project_xml(name), encoding="utf-8")
    definition_path.write_text(package_definition_xml(cfg), encoding="utf-8")
    return [project_path, definition_path]


def main(argv: list[str] | None = None) -> int:
    # argv is accepted, and ignored, so every module here has one entry-point
    # signature for tools/tasks.py to call.
    for path in write():
        print(f"  wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
