"""Cross-platform task runner.

    python -m tools.tasks build
    python -m tools.tasks check

This exists because Windows does not ship `make`, and this is an MSFS package -
practically everyone building it is on Windows. Rather than maintain the task
list twice, the logic lives here and both entry points are thin wrappers:

    Makefile   -> python -m tools.tasks <target>
    make.cmd   -> python -m tools.tasks <target>

`make.cmd` means `make build` works in cmd.exe and PowerShell with nothing
installed, because the shell resolves `make` to `make.cmd` in the working
directory. If you have real GNU Make (WSL, Git Bash, MSYS2, macOS, Linux), the
Makefile does the same thing.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from .model import REPO_ROOT

# Directories `clean` removes. Everything here is regenerated by `build`.
CLEAN_DIRS = ["build", "PackageSources/scenery", "Packages", "_PackageInt"]
CLEAN_GLOBS = ["**/__pycache__", "**/.pytest_cache"]


def _run_module(module: str, *args: str) -> int:
    """Run one of our own modules in-process.

    The argument list is always passed explicitly, even when empty. Falling
    back to a bare main() would let the module re-parse sys.argv, which still
    holds the task name and makes argparse reject it.
    """
    from importlib import import_module

    mod = import_module(f"tools.{module}")
    return mod.main(list(args))


def task_build() -> int:
    return _run_module("build")


def task_dry_run() -> int:
    return _run_module("build", "--dry-run")


def task_validate() -> int:
    return _run_module("validate")


def task_test() -> int:
    # pytest has to be a subprocess: it manipulates import state and sys.path
    # in ways that do not survive being called twice in one interpreter.
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-q"], cwd=REPO_ROOT
    )
    if result.returncode == 5:
        print("\nNo tests were collected. Is pytest installed? `pip install pytest`")
    elif result.returncode not in (0, 1):
        print(
            "\npytest did not run. Install it with:  "
            f"{Path(sys.executable).name} -m pip install pytest"
        )
    return result.returncode


def task_check() -> int:
    """The pre-commit gate. Stops at the first failure."""
    for name, task in (("validate", task_validate), ("test", task_test), ("dry-run", task_dry_run)):
        print(f"--- {name} ---")
        code = task()
        if code != 0:
            print(f"\ncheck failed at: {name}")
            return code
        print()
    print("check passed")
    return 0


def task_bindings() -> int:
    return _run_module("bind", "--list")


def task_package_def() -> int:
    return _run_module("packaging")


def task_preview() -> int:
    code = task_build()
    if code != 0:
        return code
    preview = REPO_ROOT / "build" / "preview"
    print()
    print(f"  Preview written to {preview}")
    print("    plan.svg        open in any browser - no network needed")
    print("    objects.geojson drop on geojson.io, or open in QGIS")
    return 0


def task_sweep() -> int:
    print("This needs outbound access to an Overpass API endpoint.")
    print("Running as a dry run; add --apply to write the results back:")
    print(f"    {Path(sys.executable).name} -m tools.sweep --apply")
    print()
    return _run_module("sweep")


def task_clean() -> int:
    removed = 0
    for relative in CLEAN_DIRS:
        path = REPO_ROOT / relative
        if path.exists():
            shutil.rmtree(path, ignore_errors=True)
            print(f"  removed {relative}")
            removed += 1
    for pattern in CLEAN_GLOBS:
        for path in REPO_ROOT.glob(pattern):
            if path.is_dir():
                shutil.rmtree(path, ignore_errors=True)
                removed += 1
    if not removed:
        print("  nothing to clean")
    return 0


TASKS = {
    "build": (task_build, "generate scenery XML into PackageSources/scenery/"),
    "dry-run": (task_dry_run, "generate and report without writing anything"),
    "validate": (task_validate, "check the data files and any generated XML"),
    "test": (task_test, "run the test suite"),
    "check": (task_check, "validate + test + dry-run, the pre-commit gate"),
    "bindings": (task_bindings, "show which fixture bindings are still unset"),
    "package-def": (task_package_def, "regenerate the MSFS project and package definitions"),
    "preview": (task_preview, "build, then report where the preview files are"),
    "sweep": (task_sweep, "find tall structures in OpenStreetMap (needs network)"),
    "clean": (task_clean, "remove build output and generated scenery XML"),
}


def task_help() -> int:
    launcher = Path(sys.executable).name
    print("Bring The Lights On - obstruction lighting for MSFS 2024")
    print()
    width = max(len(name) for name in TASKS)
    for name, (_, description) in TASKS.items():
        print(f"  {name:<{width}}  {description}")
    print()
    print("Run a task with any of:")
    print(f"  {launcher} -m tools.tasks <task>     works everywhere")
    print("  make <task>                      Windows (make.cmd) or GNU Make")
    print()
    print("Compiling to a .bgl needs Windows and the MSFS SDK - see docs/building.md.")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if not args or args[0] in ("help", "-h", "--help"):
        return task_help()

    name = args[0]
    # Accept the underscore spelling too; it is what a Python habit produces.
    name = name.replace("_", "-")
    if name not in TASKS:
        print(f"unknown task: {args[0]}", file=sys.stderr)
        print(f"known tasks: {', '.join(TASKS)}", file=sys.stderr)
        return 2
    return TASKS[name][0]()


if __name__ == "__main__":
    sys.exit(main())
